grid_map_visualization:
  ros__parameters:
    grid_map_topic: /grid_map

    grid_map_visualizations: [elevation_points, noisy_points, filtered_points, map_region, elevation_grid, error_grid, surface_normals, elevation_cells]

    elevation_points:
      type: point_cloud
      params:
        layer: elevation

    noisy_points:
      type: point_cloud
      params:
        layer: elevation_noisy

    filtered_points:
      type: point_cloud
      params:
        layer: elevation_filtered

    map_region:
      type: map_region
      params:
        color: 3289650
        line_width: 0.003

    elevation_grid:
      type: occupancy_grid
      params:
        layer: elevation
        data_min: 0.9
        data_max: -0.9

    error_grid:
      type: occupancy_grid
      params:
        layer: error
        data_min: -0.9
        data_max: 0.9

    surface_normals:
      type: vectors
      params:
        layer_prefix: normal_
        position_layer: elevation
        scale: 0.06
        line_width: 0.005
        color: 15600153 # red

    elevation_cells:
      type: grid_cells
      params:
        layer: elevation
        lower_threshold: -0.9
        upper_threshold: 0.9

botanbot_grid_map_node:
  ros__parameters:
    resolution: 0.2
    pcd_file_full_path: /home/ros2-foxy/f.pcd
    map_frame: odom
    topic_name: grid_map
    map_publish_fps: 10
    min_points_in_cell: 1
    cloud_transform:
      translation:
        x: 0.0
        y: 0.0
        z: 0.3
      rotation: #intrinsic rotation X-Y-Z (r-p-y)sequence
        r: 3.14
        p: 1.57
        y: 1.57
