gps_waypoint_follower:
  ros__parameters:
    number_of_gps_waypoints: 4
    gps_waypoint0: [0.0000, 0.0000]
    gps_waypoint1: [0.0000, 0.0000]
    gps_waypoint2: [0.0000, 0.0000]
    gps_waypoint3: [0.0000, 0.0000]  