#==============#
# Camera Model #
#==============#

Camera.name: "Realsense D435i"
Camera.setup: "monocular"
Camera.model: "perspective"

Camera.fx: 640.0
Camera.fy: 640.0
Camera.cx: 640.0
Camera.cy: 360.0

Camera.k1: 0.0
Camera.k2: 0.0
Camera.p1: 0.0
Camera.p2: 0.0
Camera.k3: 0.0

Camera.fps: 30.0
Camera.cols: 1280
Camera.rows: 720
Camera.focal_x_baseline: 0.49

Camera.color_order: "RGB"

#================#
# ORB Parameters #
#================#

Feature.max_num_keypoints: 5000
Feature.scale_factor: 1.2
Feature.num_levels: 11
Feature.ini_fast_threshold: 20
Feature.min_fast_threshold: 7

#=====================#
# Tracking Parameters #
#=====================#

depth_threshold: 200.0 # depth_threshold * base_line[m] = 10m
depthmap_factor: 1000.0

run_slam_rclcpp_node:
  ros__parameters:
    vocab_file_path: /home/ros2-foxy/colcon_ws/src/OUTDOOR_NAV2/botanbot_openvslam/config/orb_vocab.dbow2
    setting_file_path: /home/ros2-foxy/colcon_ws/src/OUTDOOR_NAV2/botanbot_openvslam/config/config.yaml
    mask_img_path: /home/ros2-foxy/s.txt
    map_db_path : /home/ros2-foxy/f.msg
    debug_mode: true
    eval_log: true