planner_benchmarking_rclcpp_node:
  ros__parameters:
    planner_timeout: 10.0
    interpolation_parameter: 50
    octomap_voxel_size: 0.2
    selected_state_space: "ELEVATION" # "DUBINS","REEDS", "SE2", "SE3" ### PS. Use DUBINS OR REEDS for Ackermann
    selected_planners: ["PRMstar", RRTstar]
                        #"InformedRRTstar", "BITstar", "ABITstar","AITstar", "LBTRRT",
                        #"SST", "SPARS", "SPARStwo","FMT", "CForest","AnytimePathShortening"]
    min_turning_radius: 1.5
    state_space_boundries:
      minx: -100.0
      maxx: 100.0
      miny: -100.0
      maxy: 100.0
      minz: -15.0
      maxz: 15.0
      minyaw: -3.14
      maxyaw: 3.14
    robot_body_dimens:
      x: 1.2
      y: 0.9
      z: 0.8
    start:
      z: 3.5  #3.5
    goal:
      z: 3.5 #3.5
    goal_tolerance: 0.8
    min_euclidean_dist_start_to_goal: 55.0
    batch_size: 10
    epochs: 1
    max_memory: 4096
    results_output_dir: "/home/atas/test/"   
    results_file_regex: "non"
    publish_a_sample_bencmark: true
    sample_bencmark_plans_topic: "benchmark_plan"
