pcl2octomap_converter_rclcpp_node:
  ros__parameters:
    input_pcd_filename: /home/ros2-foxy/f.pcd
    output_binary_octomap_filename: /home/ros2-foxy/f.bt
    cloud_transform:
      translation:
        x: 0.0
        y: 0.0
        z: 1.0
      rotation: #intrinsic rotation X-Y-Z (r-p-y)sequence
        r: 3.14
        p: 1.57
        y: 1.57
    downsample_voxel_size: 0.1
    remove_outlier_mean_K: 50
    remove_outlier_stddev_threshold: 0.1
    remove_outlier_radius_search: 0.1
    remove_outlier_min_neighbors_in_radius: 1
