planner_benchmarking_rclcpp_node:
  ros__parameters:
    planner_timeout: 2.0
    interpolation_parameter: 40
    octomap_topic: "octomap"
    octomap_voxel_size: 0.2
    selected_state_space: "REEDS" # "DUBINS","REEDS", "SE2" ### PS. Use DUBINS OR REEDS for Ackermann
    min_turning_radius: 2.5
    state_space_boundries:
      minx: -50.0
      maxx: 50.0
      miny: -50.0
      maxy: 50.0
      minz: -50.0
      maxz: 50.0
      minyaw: -3.14
      maxyaw: 3.14
    robot_body_dimens:
      x: 1.5
      y: 1.0
      z: 0.4  
    start:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0.0
    goal:
      x: 12.0
      y: 20.0
      z: 0.0
      yaw: 1.57 
    goal_tolerance: 0.2  
    num_benchmark_runs: 100
    max_memory: 4096
    results_output_file: "/home/ros2-foxy/outdoor_large_planbenchmarking.log"

