planner_benchmarking_rclcpp_node:
  ros__parameters:
    planner_timeout: 2.5
    interpolation_parameter: 50
    octomap_topic: "octomap"
    octomap_voxel_size: 0.2
    se2_space: "REEDS" # "DUBINS","REEDS", "SE2" ### PS. Use DUBINS OR REEDS for Ackermann
    min_turning_radius: 2.5
    state_space_boundries:
      minx: -50.0
      maxx: 50.0
      miny: -50.0
      maxy: 50.0
      minz: -50.0
      maxz: 50.0
      minyaw: -3.14
      maxyaw: 3.14
    robot_body_dimens:
      x: 1.5
      y: 1.0
      z: 0.4  
