planner_benchmarking_rclcpp_node:
  ros__parameters:
    planner_timeout: 4.0
    interpolation_parameter: 120
    octomap_topic: "octomap"
    octomap_voxel_size: 0.2
    selected_state_space: "DUBINS" # "DUBINS","REEDS", "SE2", "SE3" ### PS. Use DUBINS OR REEDS for Ackermann
    selected_planners: ["RRTstar","PRMstar","LazyPRMstar", "RRTXstatic", "FMT", "BITstar", "ABITstar", "CForest"]
    min_turning_radius: 1.5
    state_space_boundries:
      minx: -100.0
      maxx: 100.0
      miny: -30.0
      maxy: 30.0
      minz: -10.0
      maxz: 10.0
      minyaw: -3.14
      maxyaw: 3.14
    robot_body_dimens:
      x: 1.5
      y: 1.5
      z: 0.5
    start:
      x: -35.0
      y: -20.0
      z: 0.8  #3.5
      yaw: 0.0
    goal:
      x: 55.0
      y: 25.0
      z: 0.8 #3.5
      yaw: 0.0 
    goal_tolerance: 0.2  
    num_benchmark_runs: 0
    max_memory: 4096
    results_output_file: "/home/ros2-foxy/ECMR2021/benchmark_results/city_dubins_benchmark.log"
    publish_a_sample_bencmark: true
    sample_bencmark_plans_topic: "benchmark_plan"
