planner_benchmarking_rclcpp_node:
  ros__parameters:
    planner_timeout: 2.0
    interpolation_parameter: 120
    octomap_topic: "octomap"
    octomap_voxel_size: 0.2
    selected_state_space: "SE2" # "DUBINS","REEDS", "SE2", "SE3" ### PS. Use DUBINS OR REEDS for Ackermann
    min_turning_radius: 2.5
    state_space_boundries:
      minx: -100.0
      maxx: 100.0
      miny: -100.0
      maxy: 100.0
      minz: 0.0
      maxz: 4.0
      minyaw: -3.14
      maxyaw: 3.14
    robot_body_dimens:
      x: 1.5
      y: 1.5
      z: 0.4
    start:
      x: -5.0
      y: 20.0
      z: 0.9
      yaw: 0.0
    goal:
      x: 45.0
      y: -5.0
      z: 0.5
      yaw: 0.0 
    goal_tolerance: 1.0  
    num_benchmark_runs: 100
    max_memory: 4096
    results_output_file: "/home/ros2-foxy/outdoor_large_planbenchmarking.log"
    publish_a_sample_bencmark: true
    sample_bencmark_plans_topic: "benchmark_plan"
