botanbot_planner_server_rclcpp_node:
  ros__parameters:
    planner_plugin: "SE2Planner" # other options: "SE2Planner", "SE3Planner" ,"SE2PlannerControlSpace"
    expected_planner_frequency: 10.0
    SE2Planner:
      plugin: "botanbot_planning::SE2Planner"
      planner_name: "RRTStar" # other options: RRTStar, RRTConnect, KPIECE1, SBL
      planner_timeout: 3.0
      interpolation_parameter: 50
      octomap_topic: "octomap"
      octomap_voxel_size: 0.2
      se2_space: "SE2" # "DUBINS","REEDS", "SE2" ### PS. Use DUBINS OR REEDS for Ackermann
      state_space_boundries:
        minx: -50.0
        maxx: 50.0
        miny: -50.0
        maxy: 50.0
        minyaw: -3.14
        maxyaw: 3.14
      robot_body_dimens:
        x: 1.5
        y: 1.0
        z: 0.4  
    SE2PlannerControlSpace:
      plugin: "botanbot_planning::SE2PlannerControlSpace"
      planner_name: "PRMstar"  # other options: RRT, SST, EST, KPIECE1, PRMstar 
      planner_timeout: 2.0
      interpolation_parameter: 50
      octomap_topic: "octomap"
      octomap_voxel_size: 0.2
      se2_space: "REEDS" # "DUBINS","REEDS", "SE2" ### PS. Use DUBINS OR REEDS for Ackermann
      state_space_boundries:
        minx: -50.0
        maxx: 50.0
        miny: -50.0
        maxy: 50.0
        minyaw: -3.14
        maxyaw: 3.14
      velocity_space_boundries:
        min_v: -0.4
        max_v: 0.4 
      control_input_bounds:
        min_acc: -0.3
        max_acc: 0.3
        min_steer: -0.5
        max_steer: 0.5
      robot_body_dimens:
        x: 1.5
        y: 1.0
        z: 0.4  
    SE3Planner:
      plugin: "botanbot_planning::SE3Planner"
      planner_name: "RRTStar"  # other options: PRMStar, RRTStar, RRTConnect, KPIECE1, , 
      planner_timeout: 1.0
      interpolation_parameter: 25
      octomap_topic: "octomap"
      octomap_voxel_size: 0.2
      state_space_boundries:
        minx: -50.0
        maxx: 50.0
        miny: -50.0
        maxy: 50.0
        minz: 0.0
        maxz: 2.5
      robot_body_dimens:
        x: 1.5
        y: 1.0
        z: 0.2   

botanbot_controller_server_rclcpp_node:
  ros__parameters:
    controller_plugin: "MPCControllerROS" # other options: 
    controller_frequency: 15.0
    MPCControllerROS:
      plugin: "mpc_controller::MPCControllerROS"
      N: 10                                                       #timesteps in MPC Horizon
      DT: 0.2                                                     #discretization time between timesteps(s)    
      L_F: 0.66                                                   #distance from CoG to front axle(m)
      L_R: 0.66                                                   #distance from CoG to rear axle(m)
      V_MIN: -1.0                                                 #min / max velocity constraint(m / s)
      V_MAX:  1.0
      A_MIN:  -1.0                                                #min / max acceleration constraint(m / s ^ 2)
      A_MAX:   1.0
      DF_MIN:  -1.5                                               #min / max front steer angle constraint(rad)
      DF_MAX:   1.5
      A_DOT_MIN: -1.0                                             #min / max jerk constraint(m / s ^ 3)
      A_DOT_MAX:  1.0
      DF_DOT_MIN: -0.8                                            #min / max front steer angle rate constraint(rad / s)
      DF_DOT_MAX: 0.8
      Q: [10.0, 10.0, 0.1, 0.1]                                  #weights on x, y, psi, and v.
      R: [10.0, 100.0]                                            #weights on jerk and slew rate(steering angle derivative)
      debug_mode: False                                           #enable/disable debug messages
      params_configured: True      

botanbot_map_server_rclcpp_node:
  ros__parameters:
    octomap_filename: "/home/ros2-foxy/slope_map.bt"
    octomap_voxel_size: 0.2
    octomap_publish_frequency: 50
    provide_utm_to_map_transform: true
    publish_octomap_as_pointcloud: true
    octomap_publish_topic_name: "octomap" # octomap_msgs::msg::Octomap type of message topic name 
    octomap_point_cloud_publish_topic: "octomap_pointcloud" # sensor_msgs::msg::PoinCloud2 that represents octomap
    map_frame_id: "map"
    static_map_frame_id: "static_map"
    utm_frame_id: "utm"
    yaw_offset: 1.57 #see navsat_transform_node from robot_localization, this offset is needed to recorrect orientation of static map
    map_coordinates:
      latitude: 49.89996853007036
      longitude: 8.900083512416545
      altitude: 0.6342219080870174
      quaternion:
        x: -0.0002674301579378746
        y: -7.80412511940006e-05
        z: 0.7068413617683594
        w: 0.7073720461568473

