name: foxy

on: [push, pull_request]

jobs:
    job1:
        name: Build
        runs-on: ubuntu-20.04
        steps:
            - name: ROS2 Install
              run: |
                  # Ref: https://index.ros.org/doc/ros2/Installation/Foxy/Linux-Install-Debians/
                  sudo locale-gen en_US en_US.UTF-8
                  sudo update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
                  export LANG=en_US.UTF-8
                  sudo apt update && sudo apt install curl gnupg2 lsb-release
                  sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key  -o /usr/share/keyrings/ros-archive-keyring.gpg
                  echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
                  sudo apt update
                  sudo apt install ros-galactic-desktop
                  source /opt/ros/galactic/setup.bash
            - name: Create Workspace
              run: |
                  mkdir -p ~/ros2_ws/src
            - name: Install repos and dependencies
              run: |
                  source /opt/ros/galactic/setup.bash
                  sudo apt install python3-colcon-common-extensions
                  sudo apt install -y python3-rosdep2
                  sudo apt-get install python3-vcstool
                  sudo apt-get install xdotool
                  sudo apt-get install coinor-libipopt-dev
                  rosdep update
                  cd ~/ros2_ws
                  wget https://raw.githubusercontent.com/jediofgever/vox_nav/galactic/underlay.repos
                  vcs import src < underlay.repos     
                  rosdep install -y -r -q --from-paths src --ignore-src --rosdistro galactic   
                  colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release -DWITH_IPOPT=true --packages-select casadi ompl
                  sudo cp install/ompl/lib/libompl.so* /usr/local/lib/
                  sudo cp install/casadi/lib/libcasadi.so* /usr/local/lib/
            - name: Build packages
              run: |
                  source /opt/ros/foxy/setup.bash
                  cd ~/ros2_ws
                  colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release --packages-skip-regex archived --packages-skip ompl casadi vox_nav_openvslam
                  source ~/ros2_ws/install/setup.bash
